server:
  port: 9091
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    cors:
      allowed-origins: http://localhost:4200
  datasource:
    url: jdbc:mysql://localhost:4306/codewalker?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
api:
  prefix: api/v1